### ISSUE TITLE
something about python manage.py search_index --rebuild

### ISSUE THREAD

**Issue by zsk1993** [sabricot/django-elasticsearch-dsl#265]
After I entered python mange.py search_index --rebuild locally, I found that mysql and es could synchronize the data. I tried to create and update the data, and found that the data could be based on es, but the delete operation could not be updated. Thank you very much for your reply!

**Comment by safwanrahman** [comment]
@zsk1993 Can you clear about what you are facing?

**Comment by zsk1993** [comment]
I am refer to this: https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html

Populate¶
To create and populate the Elasticsearch index and mapping use the search_index command:

$ ./manage.py search_index --rebuild
Now, when you do something like:

car = Car(
    name="Car one",
    color="red",
    type=1,
    description="A beautiful car"
)
car.save()
The object will be saved in Elasticsearch too (using a signal handler).

**Comment by zsk1993** [comment]
@safwanrahman 
The above documentation says./manage.py search_index --rebuild will use the signal handler to synchronize data from mysql to es, in fact I tried to create and update the operation, which is true, but the delete operation is not synchronized, thank you!

**Comment by alexgarel** [comment]
@zsk1993 

`./manage.py search_index --rebuild` does what it says it rebuild your index. That is it first remove it, recreate it then, using data in database, it populates the index.

Because of removal / recreation of index, data which is not in the database anymore won't be present in the index. If you still see that data, maybe, you are looking at the wrong index.

Although after that, django-elasticsearch-dsl updates the index, only on the basis of what happens in the python code through Django models. So if your database has triggers, or if you update it through another software, you'll have to build your own procedures to update the index.

**Comment by zsk1993** [comment]
@alexgarel Thank you very much for your answer！ I see
