### ISSUE TITLE
Add django-elasticsearch-dsl to Python Package Index

### ISSUE THREAD

**Issue by alaminopu** [sabricot/django-elasticsearch-dsl#9]
Please add this to Python Package Index.

**Comment by sabricot** [comment]
OK, i'm gonna work on it, but there is some things to do before, like cleanning some parts and maybe try to be compatible with elasticsearch 5.

**Comment by barseghyanartur** [comment]
@sabricot:

Seems very nice (in terms of neat code and the way it integrates with Django). What's the status of the project? Really alpha or you're using it in production?

**Comment by parruc** [comment]
I also like this product's design and I'd love seeing it on pypi

**Comment by drdaeman** [comment]
This is a slightly separate issue, but as it's packaging related, I guess I'll just post it here. Before publishing, please consider listing `'django_elasticsearch_dsl.management'` and `'django_elasticsearch_dsl.management.commands'` (and, possibly, others) in `packages` parameter in `setup.py`. Either explicitly or using `find_packages` (although that one isn't available without setuptools).

Otherwise management commands won't be available.

**Comment by barseghyanartur** [comment]
@sabricot:

This can be closed.
